-- Apply once to the dedicated AUREVIA Neon database, before deployment.
-- No sample contacts and no destructive change to existing data.
CREATE TABLE IF NOT EXISTS leads (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind text NOT NULL CHECK (kind IN ('contact', 'valuation')),
  name text NOT NULL,
  surname text NOT NULL,
  email text NOT NULL,
  phone text,
  city text,
  property_type text,
  subject text,
  message text NOT NULL,
  details jsonb NOT NULL CHECK (jsonb_typeof(details) = 'object'),
  is_audit boolean GENERATED ALWAYS AS (COALESCE(jsonb_typeof(details->'auditReport') = 'object', false)) STORED,
  property_count text GENERATED ALWAYS AS (details->>'propertyCount') STORED,
  status text NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'read', 'contacted', 'appointment', 'closed', 'archived')),
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS leads_created_id_idx ON leads (created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS leads_status_created_idx ON leads (status, created_at DESC, id DESC);
REVOKE ALL ON TABLE leads FROM PUBLIC;
