import {LegalIdentityNotice,LegalLayout} from "@/components/LegalPage";
export const metadata={title:"Mentions légales"};
export default function Page(){return <LegalLayout title="Mentions légales" intro="Identification, hébergement et responsabilité du site AUREVIA.">
  <h2>1. Éditeur du site</h2><p><strong>Nom commercial :</strong> AUREVIA<br/><strong>Activité :</strong> gestion de locations courte durée, valorisation et conciergerie de propriétés<br/><strong>Zone d’intervention :</strong> Gênes et Riviera ligure, Italie<br/><strong>Courrier électronique :</strong> <a href="mailto:contatto@aurevia-genova.com">contatto@aurevia-genova.com</a><br/><strong>Site :</strong> aurevia-genova.com</p><LegalIdentityNotice/>
  <h2>2. Hébergement</h2><p>Le site est hébergé par <strong>Vercel Inc.</strong>, 440 N Barranca Avenue #4133, Covina, CA 91723, États-Unis. Site : <a href="https://vercel.com" target="_blank" rel="noreferrer">vercel.com</a>.</p>
  <h2>3. Propriété intellectuelle</h2><p>La structure du site, la marque AUREVIA, les textes, éléments graphiques, photographies, vidéos et autres contenus sont protégés par les règles applicables à la propriété intellectuelle. Sauf autorisation écrite préalable ou exception légale, leur reproduction, représentation, adaptation, extraction ou réutilisation, totale ou partielle, est interdite.</p><p>Les marques, photographies ou contenus appartenant à des tiers restent la propriété de leurs titulaires respectifs et sont utilisés avec l’autorisation ou la licence correspondante.</p>
  <h2>4. Responsabilité</h2><p>AUREVIA veille à l’exactitude et à l’actualisation des informations publiées, sans pouvoir en garantir l’exhaustivité permanente. Les projections de revenus, tarifs, taux d’occupation et estimations présentées sont indicatives : elles ne constituent ni une garantie de résultat, ni un conseil fiscal, juridique ou financier.</p><p>AUREVIA ne peut être tenue responsable d’une indisponibilité temporaire, d’un événement extérieur raisonnablement imprévisible ou du contenu de sites tiers accessibles par lien.</p>
  <h2>5. Signalement</h2><p>Pour signaler un contenu, une erreur ou une possible atteinte à vos droits, écrivez à <a href="mailto:contatto@aurevia-genova.com?subject=Signalement%20juridique">contatto@aurevia-genova.com</a> en précisant l’adresse de la page concernée.</p>
</LegalLayout>}
