import {LegalIdentityNotice,LegalLayout} from "@/components/LegalPage";
export const metadata={title:"Politique de confidentialité"};
export default function Page(){return <LegalLayout title="Politique de confidentialité" intro="Comment AUREVIA collecte, utilise et protège vos données personnelles.">
  <h2>1. Responsable du traitement</h2><p>AUREVIA détermine les finalités et les moyens des traitements réalisés au moyen du site aurevia-genova.com. Toute demande relative aux données personnelles peut être adressée à <a href="mailto:contatto@aurevia-genova.com">contatto@aurevia-genova.com</a>.</p><LegalIdentityNotice/>
  <h2>2. Données collectées</h2><p>Selon le formulaire utilisé, AUREVIA peut recevoir vos nom, prénom, adresse électronique, profil, localisation et caractéristiques du bien, objectifs, besoins, message libre et données techniques nécessaires à la sécurité et à l’acheminement de la demande. Les champs obligatoires sont signalés dans le formulaire.</p><p>L’espace d’administration peut traiter un identifiant de connexion et un cookie de session strictement nécessaire. Il est réservé à la gestion interne des propriétés.</p>
  <h2>3. Finalités et bases juridiques</h2><div className="legal-table" role="table" aria-label="Traitements de données"><div role="row"><b>Finalité</b><b>Base juridique</b><b>Conservation</b></div><div role="row"><span>Répondre aux demandes de contact et d’évaluation</span><span>Mesures précontractuelles demandées par la personne</span><span>12 mois après le dernier échange, sauf relation contractuelle</span></div><div role="row"><span>Sécuriser le site et prévenir les abus</span><span>Intérêt légitime d’AUREVIA</span><span>Journaux techniques conservés selon les durées des prestataires, au maximum 12 mois</span></div><div role="row"><span>Gérer les propriétés dans l’espace administrateur</span><span>Exécution du contrat et intérêt légitime</span><span>Pendant la gestion, puis selon les obligations légales applicables</span></div></div>
  <h2>4. Destinataires et prestataires</h2><p>Les données sont accessibles uniquement aux personnes autorisées d’AUREVIA et, dans la limite nécessaire à leur mission, à :</p><ul><li><strong>Vercel Inc.</strong>, hébergement et infrastructure technique du site ;</li><li><strong>Resend, Inc.</strong>, acheminement des demandes par courrier électronique ;</li><li>les conseils et autorités compétentes lorsqu’une obligation légale l’impose.</li></ul><p>AUREVIA ne vend ni ne loue vos données et ne les utilise pas à des fins de prospection automatisée sans base juridique appropriée.</p>
  <h2>5. Transferts internationaux</h2><p>Certains prestataires techniques sont établis aux États-Unis ou peuvent traiter des données hors de l’Espace économique européen. AUREVIA leur demande d’encadrer ces transferts au moyen des mécanismes reconnus par le RGPD, notamment une décision d’adéquation applicable ou les clauses contractuelles types de la Commission européenne.</p>
  <h2>6. Vos droits</h2><p>Vous pouvez demander l’accès à vos données, leur rectification, leur effacement, la limitation ou l’opposition au traitement, ainsi que leur portabilité lorsque les conditions légales sont réunies. Vous pouvez également retirer un consentement à tout moment, sans affecter les traitements déjà réalisés.</p><p>Adressez votre demande à <a href="mailto:contatto@aurevia-genova.com?subject=Exercice%20de%20mes%20droits%20RGPD">contatto@aurevia-genova.com</a>. Une preuve d’identité pourra être demandée uniquement en cas de doute raisonnable. Vous pouvez introduire une réclamation auprès du <a href="https://www.garanteprivacy.it/" target="_blank" rel="noreferrer">Garante per la protezione dei dati personali</a>.</p>
  <h2>7. Sécurité et mise à jour</h2><p>AUREVIA applique des mesures organisationnelles et techniques proportionnées : connexion chiffrée, accès administrateur restreint, secrets conservés hors du code public et limitation des données collectées. Cette politique peut évoluer pour refléter les changements du service ou de la réglementation.</p>
</LegalLayout>}
