"use client";
import {useState} from "react";import {useRouter} from "next/navigation";
const stepLabels=["Propriétaire","Propriété","Projet"];
export function ValuationForm(){
 const [step,setStep]=useState(0);const [status,setStatus]=useState("");const router=useRouter();
 function next(event:React.MouseEvent<HTMLButtonElement>){const form=event.currentTarget.form;if(!form)return;const fields=Array.from(form.querySelectorAll<HTMLElement>(`[data-step="${step}"] input, [data-step="${step}"] select, [data-step="${step}"] textarea`));if(fields.every(f=>!(f instanceof HTMLInputElement||f instanceof HTMLSelectElement||f instanceof HTMLTextAreaElement)||f.reportValidity()))setStep(v=>Math.min(v+1,2));}
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setStatus("Envoi en cours…");const payload=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch("/api/valuation",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(response.ok)router.push("/grazie");else setStatus("L’envoi a échoué. Veuillez réessayer dans quelques instants.");}
 return <form onSubmit={submit}>
  <div className="form-progress" aria-label={`Étape ${step+1} sur 3`}>{stepLabels.map((label,index)=><span key={label} className={index<=step?"active":""}>{index+1}<small>{label}</small></span>)}</div><input className="honeypot" name="website" tabIndex={-1} autoComplete="off"/>
  <fieldset data-step="0" hidden={step!==0}><legend>Informations du propriétaire</legend><div className="field-row"><label>Prénom<input required name="name" maxLength={80}/></label><label>Nom<input required name="surname" maxLength={80}/></label></div><div className="field-row"><label>E-mail<input required name="email" type="email" maxLength={160}/></label><label>Téléphone<input required name="phone" type="tel" maxLength={40}/></label></div></fieldset>
  <fieldset data-step="1" hidden={step!==1}><legend>Caractéristiques de la propriété</legend><div className="field-row"><label>Adresse<input required name="address"/></label><label>Ville<input required name="city"/></label></div><div className="field-row"><label>Type de bien<select name="type"><option>Appartement</option><option>Attique</option><option>Villa</option><option>Maison indépendante</option></select></label><label>Surface en m²<input required name="area" type="number" min="20"/></label></div><div className="field-row"><label>Chambres<input required name="bedrooms" type="number" min="1"/></label><label>Salles de bain<input required name="bathrooms" type="number" min="1"/></label></div><div className="field-row"><label>Capacité d’accueil<input name="capacity" type="number" min="1"/></label><label>Équipements<select name="amenities"><option>Aucun</option><option>Vue mer</option><option>Terrasse</option><option>Piscine</option><option>Parking</option><option>Plusieurs équipements</option></select></label></div></fieldset>
  <fieldset data-step="2" hidden={step!==2}><legend>Votre projet</legend><div className="field-row"><label>Bien déjà loué ?<select name="currentlyRented"><option>Non</option><option>Oui</option></select></label><label>Disponibilité annuelle<select name="availability"><option>Jusqu’à 3 mois</option><option>3 à 6 mois</option><option>6 à 9 mois</option><option>Plus de 9 mois</option></select></label></div><label>Objectif principal<select name="objective"><option>Déléguer la gestion</option><option>Optimiser les revenus</option><option>Améliorer l’expérience des voyageurs</option><option>Protéger et entretenir le bien</option><option>Recevoir une évaluation</option></select></label><label>Services souhaités<select name="services"><option>Gestion complète</option><option>Conciergerie</option><option>Accueil</option><option>Ménage et linge</option><option>Maintenance</option><option>Optimisation des revenus</option></select></label><label>Message<textarea required name="message" maxLength={2000}/></label><label><span><input required type="checkbox" name="consent"/> J’accepte que mes données soient utilisées afin d’être recontacté au sujet de ma demande.</span></label></fieldset>
  <div className="form-navigation">{step>0&&<button type="button" className="button ghost" onClick={()=>setStep(v=>v-1)}>Retour</button>}{step<2?<button type="button" className="button" onClick={next}>Continuer</button>:<button className="button" type="submit">Envoyer la demande confidentielle</button>}</div><div role="status" className="form-status">{status}</div>
 </form>;
}
