import Link from "next/link";
import {PageHero} from "@/components/PageHero";
import {LeadForm} from "@/components/LeadForm";
import {ArrowUpRight,Clock3,Mail,MapPin,ShieldCheck} from "lucide-react";
import type {Metadata} from "next";
export const metadata:Metadata={title:"Contatti",description:"Contatti AUREVIA per una valutazione riservata della Sua proprietà a Genova o in Liguria.",alternates:{canonical:"/contatti"}};
export default function Page(){
  const email=process.env.NEXT_PUBLIC_EMAIL||"contatto@aurevia-genova.com";
  return <><PageHero label="Contact" title="Parlons de votre propriété" text="Un échange confidentiel pour comprendre vos besoins, vos objectifs et les caractéristiques de votre bien." image="/images/contact/contact-still-life.webp"/><section className="section"><div className="container split contact-layout"><div className="contact-intro"><p className="eyebrow">Premier échange</p><h2 className="contact-heading"><span>Une réponse claire,</span><span>confidentielle</span><span>et personnalisée</span></h2><p>Décrivez-nous votre bien et votre situation. Nous reviendrons vers vous pour vérifier l’adéquation avec notre zone d’intervention et préparer un premier diagnostic.</p><div className="contact-panel"><div className="contact-panel-head"><div><small>Coordonnées directes</small><strong>AUREVIA · Gênes</strong></div><ShieldCheck size={22}/></div><div className="contact-details"><a className="contact-primary" href={`mailto:${email}`}><span className="contact-icon"><Mail size={18}/></span><span><small>E-mail confidentiel</small>{email}</span><ArrowUpRight size={17}/></a><div><span className="contact-icon"><MapPin size={18}/></span><span><small>Zone d’intervention</small>Gênes et Riviera ligure</span></div><div><span className="contact-icon"><Clock3 size={18}/></span><span><small>Engagement de réponse</small>Sous 1 jour ouvré</span></div></div><p className="contact-reassurance">Chaque demande est étudiée personnellement et reste strictement confidentielle.</p></div><div className="contact-feature-image" role="img" aria-label="Dossier AUREVIA préparé pour un propriétaire"/></div><div className="form-card"><p className="eyebrow">Votre demande</p><LeadForm/><p className="form-privacy">Consultez notre <Link href="/privacy">politique de confidentialité</Link> pour connaître l’utilisation de vos données et vos droits.</p></div></div></section></>;
}
